apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  completions: 10
  parallelism: 10
  template:
    spec:
      containers:
      - name: sleep
        image: busybox
        #image: us-central1-docker.pkg.dev/batch-lab/containers/busybox@sha256:e2508c9f564deedd2f73712df47567069407880b1db23401f98c1852515ebb00
        command: ["sleep"]
        args: ["6000"]
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/machine-family
                operator: In
                values:
                - n2
              - key: cloud.google.com/requested-min-cpu-platform
                operator: In
                values:
                - Intel_Cascade_Lake
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - n2-highcpu-2
  backoffLimit: 4
